spring:
  application:
    name: EUREKA-SERVER

server:
  ssl:
    enabled: true
    key-store: classpath:myCertificate.jks
    key-store-type: PKCS12
    key-store-password: rootroot
    trust-store: classpath:myCertificate.jks
    trust-store-type: PKCS12
    trust-store-password: rootroot
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false